djangoNotesApp/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    # django
    path('admin/', admin.site.urls, name='admin'),

    # users
    path('users/', include(('users.urls', 'users'), namespace='users')),

    # notes
    path('', include(('notes.urls', 'notes'), namespace='notes')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

notes/urls.py
from django.urls import path

from notes import views


urlpatterns = [

    path(
        route='', 
        view=views.FeedView.as_view(), 
        name='feed',
    ),
    path(
        route='notes/new/', 
        view=views.NewNoteView.as_view(), 
        name='new',
    ),
    path(
        route='notes/edit/<int:note_pk>',
        view=views.EditNoteView.as_view(),
        name='edit',
    ),
    path(
        route='notes/delete/<int:note_pk>',
        view=views.DeleteNoteView.as_view(),
        name='delete',
    ),
    
]

users/urls.py
from django.urls import path

from users import views


urlpatterns = [
    
    path(
        route='signup/', 
        view=views.SignupView.as_view(), 
        name="signup",
    ),
    path(
        route='logout/', 
        view=views.LogoutView.as_view(), 
        name='logout',
    ),
    path(
        route='login/', 
        view=views.LoginView.as_view(), 
        name='login',
    ),
    path(
        route='me/profile', 
        view=views.ProfileView.as_view(), 
        name='update_profile',
    ), 

]

notes/models.py
from django.contrib.auth.models import User
from django.db import models


class Note(models.Model):

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    title = models.CharField(max_length=150)
    content = models.TextField(blank=True)

    image = models.ImageField(
        upload_to='notes/images', 
        blank=True, 
        null=True,
    )

    is_active = models.BooleanField(blank=True, default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

users/models.py
from django.contrib.auth.models import User
from django.db import models
from cloudinary.models import CloudinaryField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    picture = models.ImageField(
        upload_to='users/picture', 
        blank=True, 
        null=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username

notes/forms.py
from django import forms

from notes.models import Note


class NoteForm(forms.ModelForm):

    class Meta:

        model = Note
        fields = ('title', 'content')

users/forms.py
from django.contrib.auth.models import User
from users.models import Profile

from django import forms


class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'picture']


class SignupForm(forms.Form):

    username = forms.CharField(min_length=4, max_length=16)
    email = forms.CharField(min_length=6, max_length=320, widget=forms.EmailInput())

    password = forms.CharField(min_length=8, max_length=100, widget=forms.PasswordInput())
    password_confirmation = forms.CharField(min_length=8, max_length=100, widget=forms.PasswordInput())

    def clean_username(self):
        username = self.cleaned_data['username']
        username_exists = User.objects.filter(username=username)
        if username_exists:
            raise forms.ValidationError('Username is already in use')
        return username

    def clean(self):
        data = super().clean()
        if 'password' in data and 'password_confirmation' in data:
            password = data['password']
            password_confirmation = data['password_confirmation']
        else:
            raise forms.ValidationError('Password must be 8 to 100 characters')

        if password != password_confirmation:
            raise forms.ValidationError({'password_confirmation': 'Passwords do not match'})

        return data

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

notes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from notes.forms import NoteForm

from notes.models import Note


class FeedView(LoginRequiredMixin, ListView):
    template_name = 'logged/notes/feed.html'
    model = Note
    context_object_name = 'notes'

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user).order_by('-created_at')
    

class NewNoteView(LoginRequiredMixin, CreateView):
    template_name = "logged/notes/new_note.html"
    form_class = NoteForm
    success_url = reverse_lazy('notes:feed')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EditNoteView(LoginRequiredMixin, UpdateView):
    template_name = 'logged/notes/new_note.html'
    form_class = NoteForm
    success_url = reverse_lazy('notes:feed')
    slug_field = 'pk'
    slug_url_kwarg = 'note_pk'

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)


class DeleteNoteView(LoginRequiredMixin, DeleteView):
    model = Note
    slug_field = 'pk'
    slug_url_kwarg = 'note_pk'
    template_name = 'logged/notes/delete.html'
    success_url = reverse_lazy('notes:feed')

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)

    def get(self, request, *args, **kwargs):
        return self.post(self, request, *args, **kwargs)

users/views.py
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, UpdateView
from django.urls import reverse_lazy

from users.forms import SignupForm, ProfileForm

from users.models import Profile


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'logged/users/profile.html'
    model = Profile
    form_class = ProfileForm
    success_url = reverse_lazy('users:update_profile')

    def get_object(self):
        self.old_picture = self.request.user.profile.picture
        return self.request.user.profile

    def form_valid(self, form):
        user = self.request.user
        data = form.cleaned_data
        user.first_name = data['first_name']
        user.last_name = data['last_name']
        user.save()
        self.object = form.save()
        return super(ProfileView, self).form_valid(form)


class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'users/logout.html'


class LoginView(LoginView):
    template_name = 'users/login.html'

templates/base.html
{% load static %}

<html lang="en">
  	<head>
	   <meta charset="utf-8">
	   <meta name="viewport" content="width=device-width, initial-scale=1">

	    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	    <link rel="stylesheet" href="{% static 'css/base.css' %}">
	    <link rel="icon" type="image/png" href="{% static 'assets/note.png' %}">

	    {% block headers %}{% endblock %}
    
	    <title>NotesApp</title>
  	</head>
  	<body class="m-0 row justify-content-center">

		<form class="form" method="POST" action="{{ request.path }}">
		
			{% csrf_token %}

			<div class="container-fluid logo-container mb-5">
				<img src="{% static 'assets/note.png' %}" alt="NoteApp icon" width="80" height="80">
				<span><strong>NotesApp</strong></span>
			</div>

			<div class="form-content">
			
				{% block content %}{% endblock %}
			
			</div>
		
		</form>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  	</body>
</html>

templates/logged/base.html
{% load static %}

<html lang="en">
  	<head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">

    	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    	<link rel="stylesheet" href="{% static 'css/logged/base.css' %}">

		<link rel="icon" type="image/png" href="{% static 'assets/note.png' %}">

		{% block headers %}{% endblock %}
    
    	<title>NotesApp</title>
  	</head>
  	<body class="vh-100 m-0 row justify-content-center">

		<head>
    		{% include 'logged/header.html' %}
		</head>

		<main>
			{% block content %}{% endblock %}
		</main>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  	</body>
</html>

templates/logged/header.html
{% load static %}


{% block headers %}
    <link rel="stylesheet" href="{% static 'css/logged/header.css' %}">
{% endblock %}


{% block header %}

    <header class="pt-1 pt-md-3 px-2 px-md-5">
        <nav class="navbar navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'notes:feed' %}"> 
                    <img src="{% static 'assets/note.png' %}" alt="NoteApp icon" width="40" height="40">
                    <span class="navbar-text navbar-color">NotesApp</span>
                </a>
                
                <div class="justify-content-end">

                    {% url 'notes:feed' as feed_url %}
                    {% if request.path == feed_url %}
                        <a href="{% url 'notes:new'%}">
                            <button class="btn btn-outline-warning me-5" type="button">New Note</button>
                        </a>
                    {% endif %}
                    
                    {% url 'users:update_profile' as update_profile_url %}
                    {% if request.path != update_profile_url %}
                        <a href="{% url 'users:update_profile' %}">
                            <button class="btn btn-outline-secondary ms-2" type="button">Profile</button>
                        </a>
                    {% endif %}

                    <a href="{% url 'users:logout' %}">
                        <button class="btn btn-outline-secondary ms-2" type="button">Log Out</button>
                    </a>
                </div> 
            </div>
        </nav>
    </header>

{% endblock %}
    

templates/logged/notes/feed.html
{% extends 'logged/base.html' %}
{% load static %}


{% block headers %}
    <link rel="stylesheet" href="{% static 'css/logged/notes/feed.css' %}">
{% endblock %}


{% block content %}

    {% for note in notes %}
        <div class="container note-elements">

            <a href="{% url 'notes:edit' note.pk %}" class="container-fluid note-link">
                <div class="note-text">
                    <h3> 
                        {{ note.title }} 
                    </h3>
                    <div class="note-content">
                        {{ note.content }}
                    </div>
                </div>
            </a>

            <a href="{% url 'notes:delete' note.pk %}" class="delete-button-link">
                <div class="delete-button">
                    <button class="btn btn-outline-danger"><b>×</b></button>
                </div>
            </a>

        </div>
    {% endfor %}

{% endblock %}

templates/logged/notes/new_note.html
{% extends 'logged/base.html' %}
{% load static %}


{% block headers %}
    <link rel="stylesheet" href="{% static 'css/logged/notes/new_note.css' %}">
{% endblock %}

{% block content %}

    {% url 'notes:new' as new_url %}
    {% url 'notes:edit' as edit_url %}

    <form 
        class="form" 
        method="POST" 
        action="{% if request.path == new_url %}{{ new_url }}{% else %}{{ edit_url }}{% endif %}" 
        enctype="multipart/form-data"
    >

        {% csrf_token %}

        <div class="form-content">
            <div class="form-floating mb-3">

                <input 
                    type="text" 
                    name="title" 
                    class="form-control {% if form.title.errors %} is-invalid {% endif %}" 
                    id="floatingInput" 
                    value="{% if form.errors %}{{ form.title.value }}{% else %}{{ note.title }}{% endif %}" 
                    placeholder="Title" 
                    required="true"
                />
                <label for="floatingInput">Title</label>
                <div class="invalid-feedback ms-1">
                    {% for error in form.title.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>
            
            <div class="form-floating mb-3">
                <textarea 
                    type="text"
                    name="content" 
                    class="form-control {% if form.content.errors %}is-invalid{% endif %}" 
                    id="floatingInput" 
                    placeholder="Content" 
                    style="height: 400px"
                    required="true"
                >{% if form.errors %}{{ form.content.value }}{% else %}{{ note.content }}{% endif %}</textarea>
                <label for="floatingInput">Content</label>
                <div class="invalid-feedback ms-1">
                    {% for error in form.content.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>

            <div>
                <button type="submit" class="btn btn-warning mt-3">
                    {% if request.path == new_url %}Create Note{% else %}Save{% endif %} 
                </button>
            </div>
        </div>
    </form>

{% endblock %}

templates/logged/users/profile.html
{% extends 'logged/base.html' %}
{% load static %}


{% block headers %}
    <link rel="stylesheet" href="{% static 'css/logged/users/profile.css' %}">
{% endblock %}


{% block content %}

    <form class="form" method="POST" action="{% url 'users:update_profile' %}" enctype="multipart/form-data">

        {% csrf_token %}

        <div class="container-fluid logo-container">
            {% if profile.picture %}
                <div class="image-container">
                    <img class="crop" src="{{ profile.picture.url }}" alt="User Profile Picture">
                </div>
            {% else %}
                <div class="image-container">
                    <img class="crop" src="{% static 'assets/generic_picture.png' %}" alt="User Profile Picture">
                </div>
            {% endif %}
            <span><strong>{{ user.username }}</strong></span>
        </div>

        <br><hr><br>

        <div class="form-content">
            <div class="form-floating mb-3">
                <input 
                type="text" 
                name="first_name" 
                class="form-control {% if form.first_name.errors %} is-invalid {% endif %}" 
                id="floatingInput" 
                value="{% if form.errors %}{{ form.first_name.value }}{% else %}{{ user.first_name }}{% endif %}" 
                placeholder="First Name" 
                required="true"
                />
                <label for="floatingInput">First Name</label>
                <div class="invalid-feedback ms-1">
                    {% for error in form.first_name.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>

            <div class="form-floating mb-3">
                <input 
                    type="text"
                    name="last_name" 
                    class="form-control {% if form.last_name.errors %}is-invalid{% endif %}" 
                    id="floatingInput" 
                    value="{% if form.errors %}{{ form.last_name.value }}{% else %}{{ user.last_name }}{% endif %}" 
                    placeholder="Last Name" 
                    required="true"
                />
                <label for="floatingInput">Last Name</label>
                <div class="invalid-feedback ms-1">
                    {% for error in form.last_name.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>

            <div class="input-group file-button mb-2 {% if form.picture.errors %} invalid-field {% endif %}">
                <input type="file" name="picture" class="form-control" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
            </div>

            <div style="color: #dc3545; font-size: .9em;" class="mb-3">
                {% for error in form.picture.errors %}
                    <b>Picture: </b>{{ error }}
                {% endfor %}
            </div>
            
            <div>
                <button type="submit" class="btn btn-warning">Save Changes</button>
            </div>
        </div>
    </form>

{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}


{% block headers %}
    <link rel="stylesheet" href="{% static 'css/users/login.css' %}">
{% endblock %}


{% block content %}

            {% if form.errors %}
               <p style="color: red">Invalid username or password</p>
            {% endif %}
        
            <input 
                type="text" 
                name="username" 
                placeholder="Username" 
                class="form-control"
                style="margin-top: 10px"
            />
            <input 
                type="password" 
                name="password" 
                placeholder="Password" 
                class="form-control"
            />
            <div>
                <a role="button" class="btn btn-outline-secondary me-5" href="{% url 'users:signup' %}">Sign Up</a>
                <button type="submit" class="btn btn-warning">Log In</button>
            </div>

{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% load static %}


{% block headers %}
    <link rel="stylesheet" href="{% static 'css/users/signup.css' %}">
{% endblock %}


{% block content %}

    <div class="form-floating">
        <input 
            type="text" 
            name="username"
            class="form-control {% if form.username.errors %}is-invalid{% endif %}" 
            id="floatingUsername" 
            placeholder="Username"
            value="{% if form.errors %}{{ form.username.value }}{% endif %}"
        />
        <label for="floatingUsername">Username</label>
        <div class="invalid-feedback ms-2">
            {% for error in form.username.errors %}
                {{ error }}
            {% endfor %}
        </div>
    </div>
    
    <div class="form-floating">
        <input 
            name="email"
            type="email" 
            class="form-control {% if form.email.errors %}is-invalid{% endif %}" 
            id="floatingEmail" 
            placeholder="name@example.com"
            value="{% if form.errors %}{{ form.email.value }}{% endif %}"
        />
        <label for="floatingEmail">Email</label>
        <div class="invalid-feedback ms-2">
            {% for error in form.email.errors %}
                {{ error }}
            {% endfor %}
        </div>
    </div>
    
    <div class="form-floating">
        <input 
            name="password"
            type="password" 
            class="form-control {% if form.password.errors or 'Passwords do not match' in form.password_confirmation.errors %} is-invalid {% endif %}" 
            id="floatingPassword" 
            placeholder="Password"
        />
        <label for="floatingPassword">Password</label>
        <div class="invalid-feedback ms-2">
            {% for error in form.password.errors %}
                {{ error }}
            {% endfor %}
        </div>
    </div>
    
    <div class="form-floating">
        <input 
            name="password_confirmation"
            type="password" 
            class="form-control {% if form.password_confirmation.errors %}is-invalid{% endif %}" 
            id="floatingPasswordConfirmation" 
            placeholder="Password"
        />
        <label for="floatingPasswordConfirmation">Password Confirmation</label>
        <div class="invalid-feedback ms-2">
            {% for error in form.password_confirmation.errors %}
                {{ error }}
            {% endfor %}
        </div>
    </div>

    <div class="mt-4">
        <a role="button" class="btn btn-outline-secondary me-5" href="{% url 'users:login' %}">Log In</a>
        <button type="submit" class="btn btn-warning">Sign Up</button>
    </div>
    
{% endblock %}